2023-11-29 01:57:24.184 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:04:49.160 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:04:51.540 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:04:52.769 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:05:02.395 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:05:38.337 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:05:52.454 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:14:29.189 PM: error: [object Object]
2023-11-29 02:14:52.994 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:15:04.517 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:18:01.483 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 02:53:30.632 PM: error: APIError: APIError: [object Object]
2023-11-29 02:54:20.970 PM: error: cc: APIError: [object Object]
2023-11-29 03:55:45.722 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:14:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 03:56:57.086 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:14:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 04:36:26.946 PM: error: >Could not establish a connection: 
2023-11-29 04:36:26.947 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-29 04:36:33.312 PM: error: APIError: [object Object]
    at getItemsByCatetory (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:15:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-29 04:57:52.123 PM: error: ReferenceError: Json is not defined
    at file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:21:17
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
2023-11-29 05:07:47.648 PM: error: ValidationError: "query.type" must be one of [events, bookings]
2023-11-29 05:09:29.462 PM: error: ValidationError: "query.type" must be one of [events, bookings]
2023-11-29 05:16:10.517 PM: error: ValidationError: "query.type" is required. "query.month" is required
2023-11-29 05:16:40.463 PM: error: ValidationError: "query.type" is required
2023-11-29 05:17:07.856 PM: error: ValidationError: "query.type" is required
2023-11-29 05:17:10.140 PM: error: ValidationError: "query.type" is required
2023-11-29 05:17:13.088 PM: error: ValidationError: "query.type" is required
2023-11-29 05:17:13.849 PM: error: ValidationError: "query.type" is required
2023-11-29 07:14:00.395 PM: error: 	An err has occured: 
 Cannot delete property 'meta' of [object Array]
2023-11-29 07:15:33.067 PM: error: 	An err has occured: 
 (conn=4015, no: 1060, SQLState: 42S21) Duplicate column name 'date_start'
sql: ALTER TABLE `Events` ADD `date_start` DATETIME NOT NULL; - parameters:[]
2023-11-29 07:15:33.596 PM: error: 	An err has occured: 
 Cannot delete property 'meta' of [object Array]
2023-11-29 07:17:19.574 PM: error: >Could not establish a connection: 
2023-11-29 07:17:19.575 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-29 09:06:44.753 PM: error: Error
    at Query.run (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/query.js:53:25)
    at /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async reservation.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:21)
    at async reservation.getAllReservations (file:///Users/polo/Dev/Projects/Miguels/models/reservationModel.js:14:20)
    at async file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:35:30
2023-11-29 09:07:48.023 PM: error: ReferenceError: pass is not defined
    at file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:28:9
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
2023-11-29 09:08:16.134 PM: error: Error
    at Query.run (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/query.js:53:25)
    at /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async reservation.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:21)
    at async reservation.getAllReservations (file:///Users/polo/Dev/Projects/Miguels/models/reservationModel.js:14:20)
    at async file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:36:30
2023-11-30 02:16:48.831 PM: error: TypeError: fn is not a function
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:346:12)
2023-11-30 02:18:27.819 PM: error: TypeError: Event.findAll is not a function
    at events.getAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:10:32)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:88:33)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 02:20:26.191 PM: error: TypeError: Event.findAll is not a function
    at events.findAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:10:32)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:88:33)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 02:22:13.453 PM: error: TypeError: data is not iterable
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:109:19)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 02:22:38.035 PM: error: TypeError: data is not iterable
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:109:19)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 02:23:18.189 PM: error: TypeError: data is not iterable
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:109:19)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 02:23:41.337 PM: error: TypeError: res.JSON is not a function
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:107:9)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 02:24:12.922 PM: error: ReferenceError: req is not defined
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:113:53)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 02:27:58.118 PM: error: ReferenceError: req is not defined
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:113:53)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 06:22:24.396 PM: error: ReferenceError: req is not defined
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:113:53)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 06:23:41.175 PM: error: ReferenceError: req is not defined
    at send (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:107:22)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:92:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-30 07:47:57.933 PM: error: >Could not establish a connection: 
2023-11-30 07:47:57.935 PM: error: SequelizeConnectionError: (conn=5451, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:32:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 07:48:04.770 PM: error: >Could not establish a connection: 
2023-11-30 07:48:04.771 PM: error: SequelizeConnectionError: (conn=5453, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 07:52:07.696 PM: error: >Could not establish a connection: 
2023-11-30 07:52:07.697 PM: error: SequelizeConnectionError: (conn=5464, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 07:54:36.095 PM: error: >Could not establish a connection: 
2023-11-30 07:54:36.096 PM: error: SequelizeConnectionError: (conn=5468, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 07:55:28.600 PM: error: >Could not establish a connection: 
2023-11-30 07:55:28.601 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:32:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 07:59:07.638 PM: error: >Could not establish a connection: 
2023-11-30 07:59:07.639 PM: error: SequelizeConnectionError: (conn=5472, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 07:59:10.346 PM: error: TypeError: sequelizeQuery.date_end.toIso is not a function
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:82:61)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
2023-11-30 07:59:27.376 PM: error: TypeError: sequelizeQuery.date_end.toIso is not a function
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:82:61)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
2023-11-30 07:59:29.088 PM: error: TypeError: sequelizeQuery.date_end.toIso is not a function
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:82:61)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:284:15
2023-11-30 08:01:12.576 PM: error: >Could not establish a connection: 
2023-11-30 08:01:12.578 PM: error: SequelizeConnectionError: (conn=5478, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:01:30.343 PM: error: SequelizeConnectionError: (conn=5479, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:05:54.877 PM: error: >Could not establish a connection: 
2023-11-30 08:05:54.879 PM: error: SequelizeConnectionError: (conn=5480, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:32:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:06:03.648 PM: error: SequelizeConnectionError: (conn=5481, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async events.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:21)
    at async events.findAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:12:16)
    at async getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:100:20)
2023-11-30 08:06:13.741 PM: error: >Could not establish a connection: 
2023-11-30 08:06:13.742 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:32:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:06:54.982 PM: error: >Could not establish a connection: 
2023-11-30 08:06:54.984 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:07:03.980 PM: error: >Could not establish a connection: 
2023-11-30 08:07:03.982 PM: error: SequelizeConnectionError: (conn=5497, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:32:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:12:47.389 PM: error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:89:20)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:29:15.517 PM: error: >Could not establish a connection: 
2023-11-30 08:29:15.519 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:29:34.347 PM: error: ReferenceError: logger is not defined
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:10:13)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:48:35)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:30:19.409 PM: error: ReferenceError: req is not defined
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:13:67)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:48:35)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:31:11.748 PM: error: >Could not establish a connection: 
2023-11-30 08:31:11.749 PM: error: SequelizeConnectionError: (conn=5563, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:31:32.144 PM: error: >Could not establish a connection: 
2023-11-30 08:31:32.146 PM: error: SequelizeConnectionError: (conn=5565, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:31:37.221 PM: error: ReferenceError: extracted_queries is not defined
    at file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:20:25
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:16:27)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:48:35)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
2023-11-30 08:33:24.550 PM: error: >Could not establish a connection: 
2023-11-30 08:33:24.552 PM: error: SequelizeConnectionError: (conn=5567, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:37:32.275 PM: error: ReferenceError: Op is not defined
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:48:22)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:48:43)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:37:48.665 PM: error: >Could not establish a connection: 
2023-11-30 08:37:48.666 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:37:54.462 PM: error: TypeError: Cannot read properties of undefined (reading 'toISO')
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:49:58)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:47:43)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:38:41.097 PM: error: >Could not establish a connection: 
2023-11-30 08:38:41.099 PM: error: SequelizeConnectionError: (conn=5574, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:39:01.416 PM: error: TypeError: Cannot read properties of undefined (reading 'toISO')
    at RequestUtils.convertToSequelize (file:///Users/polo/Dev/Projects/Miguels/utils/requestUtils.js:49:58)
    at getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:47:43)
    at file:///Users/polo/Dev/Projects/Miguels/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at file:///Users/polo/Dev/Projects/Miguels/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
2023-11-30 08:39:45.178 PM: error: >Could not establish a connection: 
2023-11-30 08:39:45.180 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:41:39.679 PM: error: >Could not establish a connection: 
2023-11-30 08:41:39.680 PM: error: SequelizeConnectionError: (conn=5579, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:41:49.833 PM: error: SequelizeConnectionError: (conn=5580, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async events.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:21)
    at async events.findAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:12:16)
    at async getCalendarEvents (file:///Users/polo/Dev/Projects/Miguels/controllers/publicInfoController.js:52:24)
2023-11-30 08:44:12.428 PM: error: SequelizeConnectionError: (conn=5584, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:46:41.771 PM: error: >Could not establish a connection: 
2023-11-30 08:46:41.773 PM: error: SequelizeConnectionError: (conn=5588, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 08:47:22.875 PM: error: >Could not establish a connection: 
2023-11-30 08:47:22.877 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:50:44.671 PM: error: Error: WHERE parameter "id" has invalid "undefined" value
    at MariaDBQueryGenerator.whereItemQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:13)
    at /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:25
    at Array.forEach (<anonymous>)
    at MariaDBQueryGenerator.whereItemsQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1732:35)
    at MariaDBQueryGenerator.getWhereConditions (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2075:19)
    at MariaDBQueryGenerator.selectQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:988:28)
    at MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
    at events.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async events.findAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:12:16)
2023-11-30 08:50:46.120 PM: error: Error: WHERE parameter "id" has invalid "undefined" value
    at MariaDBQueryGenerator.whereItemQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:13)
    at /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:25
    at Array.forEach (<anonymous>)
    at MariaDBQueryGenerator.whereItemsQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1732:35)
    at MariaDBQueryGenerator.getWhereConditions (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2075:19)
    at MariaDBQueryGenerator.selectQuery (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-generator.js:988:28)
    at MySQLQueryInterface.select (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
    at events.findAll (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/model.js:1140:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async events.findAllEvents (file:///Users/polo/Dev/Projects/Miguels/models/eventModel.js:12:16)
2023-11-30 08:51:32.237 PM: error: >Could not establish a connection: 
2023-11-30 08:51:32.238 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:53:21.813 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:53:27.129 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:54:03.948 PM: error: SequelizeConnectionError: (conn=5609, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 08:59:31.664 PM: error: SequelizeConnectionError: (conn=5613, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:03:55.573 PM: error: >Could not establish a connection: 
2023-11-30 09:03:55.575 PM: error: SequelizeConnectionError: (conn=5663, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:05:56.842 PM: error: APIError: Not Found
    at notFound (file:///Users/polo/Dev/Projects/Miguels/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:328:13)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:328:13)
    at /Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/polo/Dev/Projects/Miguels/node_modules/express/lib/router/index.js:346:12)
2023-11-30 09:06:28.702 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:09:55.480 PM: error: >Could not establish a connection: 
2023-11-30 09:09:55.481 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:10:10.169 PM: error: >Could not establish a connection: 
2023-11-30 09:10:10.171 PM: error: SequelizeConnectionError: (conn=5671, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:11:49.223 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 77549ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:509:9)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-11-30 09:12:09.224 PM: error: >Could not establish a connection: 
2023-11-30 09:12:09.226 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1003ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 09:12:30.572 PM: error: >Could not establish a connection: 
2023-11-30 09:12:30.574 PM: error: SequelizeConnectionError: (conn=5675, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1000ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 09:14:04.658 PM: error: >Could not establish a connection: 
2023-11-30 09:14:04.659 PM: error: SequelizeConnectionError: (conn=5679, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1001ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/sequelize.js:457:5)
    at async mariadb_connector.connect (file:///Users/polo/Dev/Projects/Miguels/config/maria_db.js:36:16)
    at async file:///Users/polo/Dev/Projects/Miguels/app.js:43:1
2023-11-30 09:14:25.720 PM: error: ValidationError: "query.id" must be a number
2023-11-30 10:24:27.306 PM: error: >Could not establish a connection: 
2023-11-30 10:24:27.307 PM: error: SequelizeConnectionError: (conn=-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1002ms
    at ConnectionManager.connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/polo/Dev/Projects/Miguels/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2023-12-01 12:08:30.567 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 12:10:56.343 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 12:10:56.800 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 12:32:07.352 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 12:33:31.628 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 01:08:47.881 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:43)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:08:51.158 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:43)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:10:01.940 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:77)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:10:11.070 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:77)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:10:41.283 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:77)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:11:35.988 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:77:88)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:12:16.124 PM: error: Error: Month string is too short
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:78:43)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:52:22.446 PM: error: Error: Invalid month string
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:85:19)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:52:32.646 PM: error: Error: Invalid month string
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:85:19)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 01:52:34.146 PM: error: Error: Invalid month string
    at #getMonthAbbreviation (file:///home/admin/dev/capstone/utils/requestUtils.js:85:19)
    at file:///home/admin/dev/capstone/utils/requestUtils.js:21:125
    at Array.forEach (<anonymous>)
    at RequestUtils.convertToSequelize (file:///home/admin/dev/capstone/utils/requestUtils.js:17:27)
    at getCalendarEvents (file:///home/admin/dev/capstone/controllers/publicInfoController.js:50:47)
    at file:///home/admin/dev/capstone/utils/catchAsync.js:10:18
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at file:///home/admin/dev/capstone/middlewares/validate.js:30:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 05:51:02.735 PM: error: ReferenceError: _ is not defined
    at file:///home/admin/dev/capstone/config/defaults.js:29:32
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/admin/dev/capstone/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
2023-12-01 06:10:51.790 PM: error: TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at file:///home/admin/dev/capstone/config/defaults.js:46:33
    at Array.forEach (<anonymous>)
    at file:///home/admin/dev/capstone/config/defaults.js:45:42
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/admin/dev/capstone/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
2023-12-01 07:07:13.403 PM: error: ValidationError: "query.hous" is not allowed
2023-12-01 09:29:07.341 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:31:01.774 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:31:06.379 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:33:52.600 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:33:56.310 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:34:21.785 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:36:22.115 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:38:50.633 PM: error: Error: No default engine was specified and no extension was provided.
    at new View (/home/admin/dev/capstone/node_modules/express/lib/view.js:61:11)
    at Function.render (/home/admin/dev/capstone/node_modules/express/lib/application.js:587:12)
    at ServerResponse.render (/home/admin/dev/capstone/node_modules/express/lib/response.js:1039:7)
    at file:///home/admin/dev/capstone/app.js:40:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 09:39:11.924 PM: error: Error: Cannot find module 'html'
Require stack:
- /home/admin/dev/capstone/node_modules/express/lib/view.js
- /home/admin/dev/capstone/node_modules/express/lib/application.js
- /home/admin/dev/capstone/node_modules/express/lib/express.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at new View (/home/admin/dev/capstone/node_modules/express/lib/view.js:81:14)
    at Function.render (/home/admin/dev/capstone/node_modules/express/lib/application.js:587:12)
    at ServerResponse.render (/home/admin/dev/capstone/node_modules/express/lib/response.js:1039:7)
    at file:///home/admin/dev/capstone/app.js:40:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
2023-12-01 09:42:40.758 PM: error: Error: ENOENT: no such file or directory, stat '/public/send_review.html'
2023-12-01 09:43:36.925 PM: error: TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/home/admin/dev/capstone/node_modules/express/lib/response.js:441:11)
    at file:///home/admin/dev/capstone/app.js:40:9
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/admin/dev/capstone/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/home/admin/dev/capstone/node_modules/serve-static/index.js:121:7)
2023-12-01 10:24:09.156 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 10:49:01.272 PM: error: ValidationError: "body.rating" is required. "body.first_name" is required
2023-12-01 10:49:46.797 PM: error: ValidationError: "body.rating" is required. "body.first_name" is required
2023-12-01 10:54:51.885 PM: error: TypeError: res.status(...).JSON is not a function
    at submitReview (file:///home/admin/dev/capstone/controllers/publicInfoController.js:76:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-01 11:23:46.710 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 11:23:47.173 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-01 11:23:47.708 PM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-02 06:05:04.240 AM: error: TypeError: res.status(...).JSON is not a function
    at submitReview (file:///home/admin/dev/capstone/controllers/publicInfoController.js:76:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-02 06:05:14.792 AM: error: TypeError: res.status(...).JSON is not a function
    at submitReview (file:///home/admin/dev/capstone/controllers/publicInfoController.js:76:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-02 06:05:14.946 AM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-02 06:05:27.923 AM: error: TypeError: res.status(...).JSON is not a function
    at submitReview (file:///home/admin/dev/capstone/controllers/publicInfoController.js:76:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-02 06:21:35.542 AM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-02 06:21:35.550 AM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-02 06:21:35.556 AM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
2023-12-02 06:22:14.684 AM: error: APIError: Not Found
    at notFound (file:///home/admin/dev/capstone/middlewares/error.js:32:14)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
    at next (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/home/admin/dev/capstone/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:328:13)
    at /home/admin/dev/capstone/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/admin/dev/capstone/node_modules/express/lib/router/index.js:346:12)
